'use client'

import { useState, useRef } from 'react'
import { useRouter } from 'next/navigation'
import Image from 'next/image'
import { createClient } from '@/lib/supabase/client'
import { processImages, getPublicUrl } from '@/lib/image/upload'
import type { Clinic, Treatment } from '@/lib/supabase/types'

interface Props {
  clinics: Clinic[]
  treatments: Treatment[]
  userId: string
}

export function ReviewForm({ clinics, treatments, userId }: Props) {
  const router = useRouter()
  const supabase = createClient()
  const fileRef = useRef<HTMLInputElement>(null)

  const [title, setTitle]             = useState('')
  const [body, setBody]               = useState('')
  const [clinicId, setClinicId]       = useState('')
  const [treatmentId, setTreatmentId] = useState('')
  const [date, setDate]               = useState('')
  const [cost, setCost]               = useState('')
  const [rating, setRating]           = useState(0)
  const [previews, setPreviews]       = useState<string[]>([])
  const [blobs, setBlobs]             = useState<Blob[]>([])
  const [submitting, setSubmitting]   = useState(false)
  const [error, setError]             = useState('')

  async function handleFiles(e: React.ChangeEvent<HTMLInputElement>) {
    if (!e.target.files) return
    try {
      const processed = await processImages(e.target.files)
      setBlobs(processed)
      setPreviews(processed.map(b => URL.createObjectURL(b)))
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : '画像処理エラー')
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError('')

    if (!title || !body) { setError('タイトルと本文は必須です'); return }
    if (body.length > 300) { setError('本文は300文字以内にしてください'); return }
    if (rating === 0) { setError('評価を選択してください'); return }

    setSubmitting(true)
    try {
      // 1. Insert review (slug auto-generated by trigger)
      const { data: review, error: reviewErr } = await supabase
        .from('reviews')
        .insert({
          slug: '',
          user_id: userId,
          clinic_id: clinicId || null,
          treatment_id: treatmentId || null,
          title,
          body,
          treatment_date: date || null,
          cost: cost ? parseInt(cost) : null,
          rating,
          status: 'pending',
        })
        .select('id, slug')
        .single()

      if (reviewErr || !review) throw reviewErr

      // 2. Upload images
      for (let i = 0; i < blobs.length; i++) {
        const path = `reviews/${userId}/${review.id}/${i}.webp`
        const { error: storageErr } = await supabase.storage
          .from('reviews')
          .upload(path, blobs[i], { contentType: 'image/webp', upsert: true })
        if (storageErr) throw storageErr

        await supabase.from('review_images').insert({
          review_id: review.id,
          storage_path: path,
          order_index: i,
        })
      }

      router.push('/mypage?posted=1')
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : '投稿に失敗しました')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6 bg-white rounded-2xl border border-gray-100 p-6">
      {error && <p className="text-red-500 text-sm">{error}</p>}

      {/* Clinic */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">クリニック</label>
        <select
          value={clinicId}
          onChange={e => setClinicId(e.target.value)}
          className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400"
        >
          <option value="">選択してください</option>
          {clinics.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
      </div>

      {/* Treatment */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">施術</label>
        <select
          value={treatmentId}
          onChange={e => setTreatmentId(e.target.value)}
          className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400"
        >
          <option value="">選択してください</option>
          {treatments.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
        </select>
      </div>

      {/* Title */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">タイトル <span className="text-red-500">*</span></label>
        <input
          type="text"
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="例: 二重整形でナチュラルな仕上がりに"
          className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400"
        />
      </div>

      {/* Body */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          口コミ本文 <span className="text-red-500">*</span>
          <span className={`ml-2 text-xs ${body.length > 300 ? 'text-red-500' : 'text-gray-400'}`}>
            {body.length} / 300文字
          </span>
        </label>
        <textarea
          value={body}
          onChange={e => setBody(e.target.value)}
          rows={5}
          placeholder="施術の感想、クリニックの雰囲気、スタッフの対応など"
          className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400 resize-none"
        />
      </div>

      {/* Rating */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">評価 <span className="text-red-500">*</span></label>
        <div className="flex gap-2">
          {[1, 2, 3, 4, 5].map(v => (
            <button
              key={v}
              type="button"
              onClick={() => setRating(v)}
              className={`text-2xl transition ${v <= rating ? 'text-yellow-400' : 'text-gray-200 hover:text-yellow-200'}`}
            >
              ★
            </button>
          ))}
        </div>
      </div>

      {/* Date */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">施術日（年月）</label>
        <input
          type="month"
          value={date}
          onChange={e => setDate(e.target.value)}
          className="border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400"
        />
      </div>

      {/* Cost */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">費用（円）</label>
        <input
          type="number"
          value={cost}
          onChange={e => setCost(e.target.value)}
          placeholder="30000"
          min="0"
          className="border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-400"
        />
      </div>

      {/* Images */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          写真（最大5枚・各5MB以内）
        </label>
        <input
          ref={fileRef}
          type="file"
          accept=".jpg,.jpeg,.png,.heic,.webp"
          multiple
          onChange={handleFiles}
          className="hidden"
        />
        <button
          type="button"
          onClick={() => fileRef.current?.click()}
          className="border-2 border-dashed border-gray-200 rounded-xl px-6 py-4 text-sm text-gray-400 hover:border-brand-400 hover:text-brand-500 transition w-full"
        >
          + 画像を選択 (.jpg / .png / .heic)
        </button>
        {previews.length > 0 && (
          <div className="flex gap-2 mt-3 flex-wrap">
            {previews.map((src, i) => (
              <div key={i} className="relative w-20 h-20 rounded-lg overflow-hidden border border-gray-100">
                <Image src={src} alt={`preview-${i}`} fill className="object-cover" sizes="80px" />
              </div>
            ))}
          </div>
        )}
      </div>

      <button
        type="submit"
        disabled={submitting}
        className="w-full bg-brand-600 text-white py-3 rounded-xl font-medium hover:bg-brand-700 transition disabled:opacity-50"
      >
        {submitting ? '投稿中...' : '口コミを投稿する'}
      </button>
    </form>
  )
}
